name: Conventional Commits Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  convco-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run convco check on PR commits
        uses: convco/convco-action
        with:
          command: check
